In [3]:
# 1번 문항
import numpy as np

arr1 = np.random.rand(5,3) # 무작위 데이터 5*3 행렬 
arr2 = np.random.rand(3,2) # 무작위 데이터 3*2 행렬

dot = np.dot(arr1, arr2)
print( dot, dot.shape) # 5*2 행렬 만들어진것 확인 가능


[[1.31605744 1.28383717]
 [1.00559363 0.70935857]
 [0.93344575 0.90913426]
 [0.99016366 1.02043878]
 [0.70826405 0.60397765]] (5, 2)


In [9]:
# 2번 문항
arr1 = np.array([ [5,7], [9,7] ], float)
arr2 = np.array([ [2,4], [6,8] ], float)

concat_1 = np.concatenate((arr1,arr2), axis=0) #열방향(axis 0) concat 
concat_2 = np.concatenate((arr1,arr2), axis=1) #행방향(axis 1) concat

print( concat_1 , concat_1.shape)
print( concat_2 , concat_1.shape)


[[5. 7.]
 [9. 7.]
 [2. 4.]
 [6. 8.]] (4, 2)
[[5. 7. 2. 4.]
 [9. 7. 6. 8.]] (4, 2)


In [23]:
# 3번 문항
xy = np.array( [[1., 2., 3., 4., 6.] , 
              [10., 20., 30., 40., 50., 60.]])
print(xy)

x_train = xy[0]  
y_train = xy[1] 

print(x_train)
print(y_train)



[list([1.0, 2.0, 3.0, 4.0, 6.0])
 list([10.0, 20.0, 30.0, 40.0, 50.0, 60.0])]
[1.0, 2.0, 3.0, 4.0, 6.0]
[10.0, 20.0, 30.0, 40.0, 50.0, 60.0]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until


In [26]:
# 4번 문항

beta_gd = np.random.rand(1) # W
bias = np.random.rand(1)    # 절편

print(beta_gd, bias)


[0.049095] [0.30665116]


In [47]:
# 5번 문항
import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.],
               [10., 20., 30., 40., 50., 60.]])
x_train = xy[0]
y_train = xy[1]

beta_gd = np.random.rand(1)
bias = np.random.rand(1)

learning_rate = 0.001 # 학습률

for i in range(1000) :
    pred = (x_train * beta_gd) + bias  # x * 기울기 + 절편
    error = ((pred - y_train) ** 2 ).mean() # 에러(목적식)는 차이의 제곱을 이용해서 계산

    gd_w = ((pred - y_train) * 2 * x_train).mean() # ((y-y^)^2) w에 대한 편미분
    gd_b = ((pred - y_train) * 2).mean() # ((y-y^)^2) b에 대한 편미분

    beta_gd -= learning_rate * gd_w 
    bias -= learning_rate * gd_b

    
    if i % 100 == 0:
        print('Epoch ({:10d}/1000) error: {:10f} , beta_gd : {: 10f} , bias : {:10f}'.format(i, error, beta_gd.item(), bias.item())) # 학습 100 단위로 error, 직선의 기울기. 절편 확인 

Epoch (         0/1000) error: 1463.055637 , beta_gd :   0.445633 , bias :   0.201438
Epoch (       100/1000) error:   3.155193 , beta_gd :   9.130491 , bias :   2.142832
Epoch (       200/1000) error:   0.889183 , beta_gd :   9.485433 , bias :   2.141654
Epoch (       300/1000) error:   0.823505 , beta_gd :   9.516443 , bias :   2.067826
Epoch (       400/1000) error:   0.765525 , beta_gd :   9.534262 , bias :   1.993823
Epoch (       500/1000) error:   0.711631 , beta_gd :   9.550975 , bias :   1.922363
Epoch (       600/1000) error:   0.661531 , beta_gd :   9.567070 , bias :   1.853460
Epoch (       700/1000) error:   0.614959 , beta_gd :   9.582587 , bias :   1.787027
Epoch (       800/1000) error:   0.571665 , beta_gd :   9.597549 , bias :   1.722974
Epoch (       900/1000) error:   0.531419 , beta_gd :   9.611974 , bias :   1.661218
