<a href="https://colab.research.google.com/github/martinlee192/AI-basic/blob/master/Multivariate_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


Naive Data representation

In [56]:
torch.manual_seed(1) #랜덤함수를 고정시킴
torch.rand(5)

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])

In [35]:
#데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [40]:
#모델 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True) 

# requires_grad 가 무엇인지
# => 학습할 데이터라고 명시하는 것

#optimizer 설정
optimizer = optim.SGD([w1,w2,w3,b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    #H(x) 계산
    hypothesis = x1_train*w1 + x2_train*w2 + x3_train*w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train)**2)

    # cost로 H(x) 개선, 항상 붙어다니는 3줄
    optimizer.zero_grad()   # Gradient 초기화
    cost.backward()         # Gradient 계산
    optimizer.step()        # Wegit, bias 개선

    #error = y - x @ beta
    #grad = -transpose(X) @ error
    #beta = beta - lr*grad




    #100번 마다 로그 출력
    if epoch % 100 == 0 :
        print('Epoch {:4d}/{} w1 : {:.3f} w2 : {:.3f} w3 : {:.3f} b: {:.3f} Cost : {:.6f}'.format(epoch, nb_epochs, w1.item(),w2.item(),w3.item(),b.item(), cost.item() ))
   






Epoch    0/1000 w1 : 0.294 w2 : 0.294 w3 : 0.297 b: 0.003 Cost : 29661.800781
Epoch  100/1000 w1 : 0.674 w2 : 0.661 w3 : 0.676 b: 0.008 Cost : 1.563628
Epoch  200/1000 w1 : 0.679 w2 : 0.655 w3 : 0.677 b: 0.008 Cost : 1.497595
Epoch  300/1000 w1 : 0.684 w2 : 0.649 w3 : 0.677 b: 0.008 Cost : 1.435044
Epoch  400/1000 w1 : 0.689 w2 : 0.643 w3 : 0.678 b: 0.008 Cost : 1.375726
Epoch  500/1000 w1 : 0.694 w2 : 0.638 w3 : 0.678 b: 0.009 Cost : 1.319507
Epoch  600/1000 w1 : 0.699 w2 : 0.633 w3 : 0.679 b: 0.009 Cost : 1.266222
Epoch  700/1000 w1 : 0.704 w2 : 0.627 w3 : 0.679 b: 0.009 Cost : 1.215703
Epoch  800/1000 w1 : 0.709 w2 : 0.622 w3 : 0.679 b: 0.009 Cost : 1.167810
Epoch  900/1000 w1 : 0.713 w2 : 0.617 w3 : 0.680 b: 0.009 Cost : 1.122429
Epoch 1000/1000 w1 : 0.718 w2 : 0.613 w3 : 0.680 b: 0.009 Cost : 1.079390


Matrix Data Represenstation
$$
\begin{pmatrix}
x_1 & x_2 & x_3
\end{pmatrix}
\cdot
\begin{pmatrix}
w_1 \\
w_2 \\
w_3 \\
\end{pmatrix}
=
\begin{pmatrix}
x_1w_1 + x_2w_2 + x_3w_3
\end{pmatrix}
$$



$$ H(X) = XW $$

In [21]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [28]:
print(x_train, x_train.shape)
print(y_train, y_train.shape)

tensor([[ 73.,  80.,  75.],
        [ 93.,  88.,  93.],
        [ 89.,  91.,  90.],
        [ 96.,  98., 100.],
        [ 73.,  66.,  70.]]) torch.Size([5, 3])
tensor([[152.],
        [185.],
        [180.],
        [196.],
        [142.]]) torch.Size([5, 1])


In [33]:
#모델 초기화
W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

#optimizer 설정
optimizer = optim.SGD([W,b], lr=1e-5)

nb_epochs = 1000

for epoch in range(nb_epochs + 1) :
    #H(x)
    hypothesis = x_train.matmul(W) + b

    #Cost 계산
    cost = torch.mean((hypothesis - y_train)**2)

    #cost로 H(X) 개선 gradient decent
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch %100 == 0 : 
        print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
        ))

Epoch    0/1000 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch  100/1000 hypothesis: tensor([152.7691, 183.6985, 180.9591, 197.0627, 140.1336]) Cost: 1.563628
Epoch  200/1000 hypothesis: tensor([152.7273, 183.7273, 180.9465, 197.0517, 140.1731]) Cost: 1.497595
Epoch  300/1000 hypothesis: tensor([152.6866, 183.7554, 180.9343, 197.0409, 140.2116]) Cost: 1.435044
Epoch  400/1000 hypothesis: tensor([152.6470, 183.7827, 180.9224, 197.0304, 140.2491]) Cost: 1.375726
Epoch  500/1000 hypothesis: tensor([152.6085, 183.8093, 180.9108, 197.0201, 140.2856]) Cost: 1.319507
Epoch  600/1000 hypothesis: tensor([152.5711, 183.8352, 180.8996, 197.0101, 140.3211]) Cost: 1.266222
Epoch  700/1000 hypothesis: tensor([152.5346, 183.8604, 180.8887, 197.0003, 140.3557]) Cost: 1.215703
Epoch  800/1000 hypothesis: tensor([152.4992, 183.8849, 180.8780, 196.9908, 140.3895]) Cost: 1.167810
Epoch  900/1000 hypothesis: tensor([152.4647, 183.9087, 180.8677, 196.9814, 140.4223]) Cost: 1.122429
Epoch 

## High-level Implementation with `nn.Module`

In [42]:
class LinearRegressionModel(nn.Module):
    def __init__(self) :
        super().__init__()
        self.linear = nn.Linear(1,1)  # x input 1,1 dim

    def forward(self, x) :
        return self.linear(x)

In [43]:
#예제 사용을 위해 이름만 바꿔서 다시 정의, dim 1->3
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self) :
        super().__init__()
        self.linear = nn.Linear(3,1)  # x input 3,1 dim

    def forward(self, x) :
        return self.linear(x)

In [72]:

# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 모델 초기화
model = MultivariateLinearRegressionModel() # 위에 만들었던 클레스

#optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1e-5) #optimizer = optim.SGD([W,b], lr=1e-5)

#print(model.parameters())
# W,b 를 넣어줄 필요가 없어짐, nn.Module 상속한 클래스 통해서 자연스럽게 들어가는듯

nb_epoch = 20

for epoch in range(nb_epoch +1):
    #H(x)
    prediction = model(x_train)

    #cost 계산 torch.nn.functional의 mse 손실함수 사용
    cost = F.mse_loss(prediction, y_train)

    #cost로 H(X) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epoch, cost.item()
        ))

    


Epoch    0/20 Cost: 30431.457031
Epoch    1/20 Cost: 9540.133789
Epoch    2/20 Cost: 2991.811768
Epoch    3/20 Cost: 939.261719
Epoch    4/20 Cost: 295.894836
Epoch    5/20 Cost: 94.233376
Epoch    6/20 Cost: 31.022274
Epoch    7/20 Cost: 11.208364
Epoch    8/20 Cost: 4.997212
Epoch    9/20 Cost: 3.049662
Epoch   10/20 Cost: 2.438606
Epoch   11/20 Cost: 2.246437
Epoch   12/20 Cost: 2.185588
Epoch   13/20 Cost: 2.165900
Epoch   14/20 Cost: 2.159098
Epoch   15/20 Cost: 2.156359
Epoch   16/20 Cost: 2.154869
Epoch   17/20 Cost: 2.153797
Epoch   18/20 Cost: 2.152813
Epoch   19/20 Cost: 2.151920
Epoch   20/20 Cost: 2.151002
